// components/kmp.jsx
import * as React from 'react'

function Box({ char, className = '' }) {
  return (
    <div
      className={`-ml-0.5  w-9 h-9 text-sm md:text-base min-w-0 border-2 border-black flex justify-center gap items-center bg-gray-50 ${className}`}
    >
      {char}
    </div>
  )
}

export function KMPDemo1() {
  const [offset, setOffset] = React.useState(0)
  const T = 'abcabx?'
  const P = 'abcabd'
  return (
    <div className="border-2 border-dashed rounded-lg border-gray-400 p-4">
      <div className="flex flex-row">
        {Array.from(T).map((char, i) => (
          <Box key={i} char={char} />
        ))}
      </div>
      <div
        className={`inline-flex flex-row mt-2 relative`}
        style={{
          left: `${(offset * 8.5) / 4}rem`,
        }}
      >
        {Array.from(P).map((char, i) => {
          const color = T[i + offset] === P[i] ? 'bg-green-300' : 'bg-red-300'
          return <Box key={i} char={char} className={color} />
        })}
      </div>
      <div className="mt-2">
        <button
          type="button"
          className="btn-small"
          onClick={() => offset > 0 && setOffset(offset - 1)}
        >
          向左移动
        </button>
        <button
          type="button"
          className="btn-small ml-2"
          onClick={() => offset < 3 && setOffset(offset + 1)}
        >
          向右移动
        </button>
      </div>
    </div>
  )
}

export function KMPDemo2() {
  const T = 'abcabdddabcabc'
  const index = Array.from(Array(14)).map((_, i) => i + 1)
  index[5] = 'now'
  index[13] = 'x'
  const next = '0001200012345?'
  return (
    <div className="border-2 border-dashed rounded-lg border-gray-400 p-2 md:p-4">
      <div className="flex flex-row items-center">
        <label className="w-20 hidden md:block">主串 T：</label>
        <label className="w-4 text-sm md:hidden">T：</label>
        {Array.from(T).map((char, i) => {
          let color = ''
          if (i < 5 || (i >= 8 && i <= 12)) {
            color = 'bg-green-300'
          }
          if (i === 5 || i === 13) {
            color = 'bg-red-300'
          }
          return <Box key={i} char={char} className={color} />
        })}
      </div>
      <div className={`flex flex-row mt-2 items-center`}>
        <label className="w-20 hidden md:block">Index：</label>
        <label className="w-4 text-sm md:hidden">I：</label>
        {Array.from(index).map((char, i) => (
          <Box key={i} char={char} />
        ))}
      </div>
      <div className={`flex flex-row mt-2 items-center`}>
        <label className="w-20 hidden md:block">模式串 P：</label>
        <label className="w-4 text-sm md:hidden">P：</label>
        {Array.from(next).map((char, i) => (
          <Box key={i} char={char} />
        ))}
      </div>
    </div>
  )
}

// src/lib/components/KMP.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  
  export let demo: 1 | 2 = 1
  
  let offset = 0
  
  function Box(char: string, className = '') {
    return `<div class="-ml-0.5 w-9 h-9 text-sm md:text-base min-w-0 border-2 border-black flex justify-center gap items-center bg-gray-50 ${className}">${char}</div>`
  }
</script>

{#if demo === 1}
  <div class="border-2 border-dashed rounded-lg border-gray-400 p-4">
    <div class="flex flex-row">
      {#each Array.from('abcabx?') as char, i}
        <div class="-ml-0.5 w-9 h-9 text-sm md:text-base min-w-0 border-2 border-black flex justify-center gap items-center bg-gray-50">
          {char}
        </div>
      {/each}
    </div>
    <div
      class="inline-flex flex-row mt-2 relative"
      style="left: {(offset * 8.5) / 4}rem"
    >
      {#each Array.from('abcabd') as char, i}
        {@const T = 'abcabx?'}
        {@const color = T[i + offset] === char ? 'bg-green-300' : 'bg-red-300'}
        <div class="-ml-0.5 w-9 h-9 text-sm md:text-base min-w-0 border-2 border-black flex justify-center gap items-center bg-gray-50 {color}">
          {char}
        </div>
      {/each}
    </div>
    <div class="mt-2">
      <button
        type="button"
        class="btn-small"
        on:click={() => offset > 0 && (offset = offset - 1)}
      >
        向左移动
      </button>
      <button
        type="button"
        class="btn-small ml-2"
        on:click={() => offset < 3 && (offset = offset + 1)}
      >
        向右移动
      </button>
    </div>
  </div>
{:else if demo === 2}
  {@const T = 'abcabdddabcabc'}
  {@const index = Array.from(Array(14)).map((_, i) => i + 1)}
  {@const indexWithMarkers = [...index]}
  <!-- index[5] = 'now', index[13] = 'x' -->
  {@const next = '0001200012345?'}
  
  <div class="border-2 border-dashed rounded-lg border-gray-400 p-2 md:p-4">
    <div class="flex flex-row items-center">
      <label class="w-20 hidden md:block">主串 T：</label>
      <label class="w-4 text-sm md:hidden">T：</label>
      {#each Array.from(T) as char, i}
        {@const color = (i < 5 || (i >= 8 && i <= 12)) ? 'bg-green-300' : (i === 5 || i === 13) ? 'bg-red-300' : ''}
        <div class="-ml-0.5 w-9 h-9 text-sm md:text-base min-w-0 border-2 border-black flex justify-center gap items-center bg-gray-50 {color}">
          {char}
        </div>
      {/each}
    </div>
    <div class="flex flex-row mt-2 items-center">
      <label class="w-20 hidden md:block">Index：</label>
      <label class="w-4 text-sm md:hidden">I：</label>
      {#each indexWithMarkers as char, i}
        {@const displayChar = i === 5 ? 'now' : i === 13 ? 'x' : char}
        <div class="-ml-0.5 w-9 h-9 text-sm md:text-base min-w-0 border-2 border-black flex justify-center gap items-center bg-gray-50">
          {displayChar}
        </div>
      {/each}
    </div>
    <div class="flex flex-row mt-2 items-center">
      <label class="w-20 hidden md:block">模式串 P：</label>
      <label class="w-4 text-sm md:hidden">P：</label>
      {#each Array.from(next) as char}
        <div class="-ml-0.5 w-9 h-9 text-sm md:text-base min-w-0 border-2 border-black flex justify-center gap items-center bg-gray-50">
          {char}
        </div>
      {/each}
    </div>
  </div>
{/if}
